import { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { HiSearch } from 'react-icons/hi';
import catalogue from '../data/catalogue.generated.json';

/*
 * The catalogue renders MEASURED scores. It is generated by
 * scripts/gen-catalogue.cjs from FLORES-200 results; do not hand-write a
 * number into this file.
 *
 * What was here before: 34 models that do not exist, each with an invented
 * accuracy figure, an invented download count and an invented training-set
 * size, rendered as five-star ratings. A developer — the entire audience for
 * this site — can check any of that in about five minutes.
 *
 * The pairs that scored badly are shown, not filtered out. Publishing the
 * whole distribution is the point: nobody else has long-tail translation
 * quality data to publish, so an honest bad score is worth more here than a
 * flattering invented one.
 */

const { models, totals, bands, _method } = catalogue;

const BAND_STYLE = {
  Excellent: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
  Good: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
  Usable: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
  Limited: 'bg-orange-500/10 text-orange-400 border-orange-500/30',
  'Not recommended': 'bg-red-500/10 text-red-400 border-red-500/30',
};

const FILTERS = ['All', 'Excellent', 'Good', 'Usable', 'Limited', 'Not recommended'];

export default function ModelCatalog() {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All');
  const [limit, setLimit] = useState(48);

  const shown = useMemo(() => {
    const q = query.trim().toLowerCase();
    return models.filter((m) => {
      if (filter !== 'All' && m.band !== filter) return false;
      if (!q) return true;
      return (
        m.srcName.toLowerCase().includes(q) ||
        m.tgtName.toLowerCase().includes(q) ||
        m.id.toLowerCase().includes(q)
      );
    });
  }, [query, filter]);

  return (
    <section id="models" className="py-24 px-6 bg-gray-950">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-6"
        >
          <h2 className="text-4xl md:text-5xl font-black mb-4">
            The <span className="gradient-text">Catalogue</span>
          </h2>
          <p className="text-lg text-gray-400 max-w-3xl mx-auto">
            Every pair below was benchmarked on FLORES-200 and is listed with the score it
            earned — including the ones that scored badly.
          </p>
        </motion.div>

        {/* Method stated up front rather than buried in a footnote */}
        <div className="max-w-3xl mx-auto mb-10 text-center">
          <p className="text-xs text-gray-500 leading-relaxed">
            {_method.metric} on {_method.benchmark}, measured {_method.measured}.{' '}
            {_method.why} {_method.caveat} Bands: Excellent {bands.excellent}, Good{' '}
            {bands.good}, Usable {bands.usable}, Limited {bands.limited}, Not recommended{' '}
            {bands.notRecommended}.
          </p>
        </div>

        {/* The distribution IS the headline */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3 max-w-4xl mx-auto mb-10">
          {[
            ['Excellent', totals.excellent],
            ['Good', totals.good],
            ['Usable', totals.usable],
            ['Limited', totals.limited],
            ['Not recommended', totals.notRecommended],
          ].map(([label, n]) => (
            <div key={label} className="text-center p-3 rounded-xl bg-gray-900/60 border border-gray-800">
              <div className="text-2xl font-black text-white">{n}</div>
              <div className="text-[11px] text-gray-500 mt-1">{label}</div>
            </div>
          ))}
        </div>

        <p className="text-center text-xs text-gray-500 mb-10 max-w-3xl mx-auto">
          {totals.scored} pairs scored · median chrF++ {totals.medianChrf} ·{' '}
          <strong className="text-gray-400">{totals.notScored} more</strong> are in languages
          FLORES-200 does not cover, so they are reported as unmeasured rather than given a
          score they did not earn.
        </p>

        <div className="flex flex-col sm:flex-row gap-3 max-w-3xl mx-auto mb-8">
          <div className="relative flex-1">
            <HiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500" size={18} />
            <input
              value={query}
              onChange={(e) => { setQuery(e.target.value); setLimit(48); }}
              placeholder="Search a language — Welsh, Tumbuka, Japanese…"
              className="w-full pl-12 pr-4 py-3 bg-gray-900 border border-gray-800 rounded-xl text-sm text-white placeholder-gray-600 focus:outline-none focus:border-blue-500"
            />
          </div>
          <select
            value={filter}
            onChange={(e) => { setFilter(e.target.value); setLimit(48); }}
            className="px-4 py-3 bg-gray-900 border border-gray-800 rounded-xl text-sm text-white focus:outline-none focus:border-blue-500"
          >
            {FILTERS.map((f) => <option key={f} value={f}>{f}</option>)}
          </select>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {shown.slice(0, limit).map((m) => (
            <div
              key={m.id}
              className="bg-gray-900/60 border border-gray-800 rounded-xl p-4 hover:border-gray-700 transition-colors"
            >
              <div className="flex items-start justify-between gap-2 mb-2">
                <div className="font-semibold text-white text-sm">
                  {m.srcName} → {m.tgtName}
                </div>
                <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold border whitespace-nowrap ${BAND_STYLE[m.band]}`}>
                  {m.band}
                </span>
              </div>
              <div className="flex items-baseline gap-3 text-xs text-gray-500">
                <span>chrF++ <strong className="text-gray-300">{m.chrf2}</strong></span>
                <span>BLEU <strong className="text-gray-300">{m.bleu}</strong></span>
              </div>
              <code className="block mt-2 text-[10px] text-gray-600 truncate">{m.repo}</code>
            </div>
          ))}
        </div>

        {shown.length > limit && (
          <div className="text-center mt-8">
            <button
              onClick={() => setLimit(limit + 96)}
              className="px-6 py-3 border border-gray-700 hover:bg-gray-800 rounded-xl text-sm font-medium transition-colors"
            >
              Show more ({shown.length - limit} remaining)
            </button>
          </div>
        )}
        {shown.length === 0 && (
          <p className="text-center text-sm text-gray-500 py-12">
            No pair matches that. Try a language name.
          </p>
        )}
      </div>
    </section>
  );
}
